apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
spec:
  type: NodePort # ใช้ NodePort เพื่อเปิดพอร์ตของเครื่อง Ubuntu
  selector:
    app: guestbook # ต้องชื่อเดียวกับ Label ใน Deployment
  ports:
    - port: 80       # พอร์ตภายใน Service
      targetPort: 80 # พอร์ตที่ Container รันอยู่
      nodePort: 30080 # พอร์ตที่เราจะเข้าผ่าน Browser (เลือกได้ช่วง 30000-32767)
